"""inicio_limpio_v3

Revision ID: 2f8aa8890c03
Revises: 
Create Date: 2025-11-20 17:37:54.674014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f8aa8890c03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_keyword', sa.Column('puntos_nombre', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('ca_keyword', sa.Column('puntos_descripcion', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('ca_keyword', sa.Column('puntos_productos', sa.Integer(), nullable=False, server_default='0'))
    op.drop_index(op.f('ix_ca_keyword_tipo'), table_name='ca_keyword')
    op.drop_column('ca_keyword', 'puntos')
    op.drop_column('ca_keyword', 'tipo')
    op.drop_column('ca_licitacion', 'puntaje_detalle')
    op.drop_column('ca_licitacion', 'plazo_entrega')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_licitacion', sa.Column('plazo_entrega', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ca_licitacion', sa.Column('puntaje_detalle', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ca_keyword', sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('ca_keyword', sa.Column('puntos', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_ca_keyword_tipo'), 'ca_keyword', ['tipo'], unique=False)
    op.drop_column('ca_keyword', 'puntos_productos')
    op.drop_column('ca_keyword', 'puntos_descripcion')
    op.drop_column('ca_keyword', 'puntos_nombre')
    # ### end Alembic commands ###
