"""agregar_plazo_y_detalle

Revision ID: 8cbd15404eb0
Revises: e5a724b567c2
Create Date: 2025-11-24 18:00:28.330674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbd15404eb0'
down_revision: Union[str, Sequence[str], None] = 'e5a724b567c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_licitacion', sa.Column('plazo_entrega', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ca_licitacion', 'plazo_entrega')
    # ### end Alembic commands ###
