"""agrega puntaje_detalle

Revision ID: e5a724b567c2
Revises: f50f1881aac1
Create Date: 2025-11-21 19:25:13.832315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a724b567c2'
down_revision: Union[str, Sequence[str], None] = 'f50f1881aac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_licitacion', sa.Column('puntaje_detalle', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ca_licitacion', 'puntaje_detalle')
    # ### end Alembic commands ###
