"""actualizar_keywords_puntajes

Revision ID: f50f1881aac1
Revises: 2f8aa8890c03
Create Date: 2025-11-21 15:11:34.446737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50f1881aac1'
down_revision: Union[str, Sequence[str], None] = '2f8aa8890c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
